rfcs/rfc-template-00.md

Signed-off-by: Thor Wolpert <thor@wolpert.ca>

adding first pass RFC template

---

rfcs/rfc-added-fields-NR.MD

Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>

added new fields for consumption date

---

.github/ISSUE_TEMPLATE/pre_release_checklist.md

Signed-off-by: Lane <JAMLANE@BCGOV>

QA - define pre-release checklist and prod smoke test suite #248

---

.github/PULL_REQUEST_TEMPLATE.md
vue-project-stub/.vuerc
vue-project-stub/README.md

*Issue #:* #175 
Added defaults file (.vuerc) with updated readme instructions.
Also added PR template to this repo.

Added defaults file (.vuerc) with updated readme instructions.

---

.github/ISSUE_TEMPLATE/feature.md
docs/coding-standards/accessibility.md

*Issue #:* bcgov/entity#584
Created accessibility checklist and added to Def of Done in feature ticket template.

584 accessibility checklist

---

e2e/Jenkinsfile
e2e/README.md
e2e/globals.js
e2e/nightwatch.json
e2e/package.json
e2e/specs/test.js
e2e/templates/bddstack.bc.yaml
e2e/templates/e2e-pipeline.json
e2e/templates/e2e.param

*Issue #:*
#637 
#638 
Created basic pipeline with stub Nightwatch project. Includes base image that the tests run on.

E2e pipeline

---

api-e2e/Jenkinsfile
api-e2e/templates/E2E_Pipeline.param
api-e2e/templates/E2E_build.json
api-e2e/test.json
e2e/Jenkinsfile
e2e/nightwatch.json
e2e/package.json
e2e/specs/test.js

*Issue #:*
#748 
Added API-E2E folder

#748 Implement API E2E pipeline for coops

---

e2e/conf/local.conf.js
e2e/conf/single.conf.js
e2e/conf/test-globals.js
e2e/package.json
e2e/tests/coops/COA.JS
e2e/tests/coops/COD.JS
e2e/tests/coops/ar.js

Added coop data to global files, updated package.json to be able to run against test without refactoring tests.
Within AR script:
- Added director count assertion
- Added fee calculator assertions
- Pulled test data from globals as needed.

Added director count and fee assertions. Added default and test globals

---

api-e2e/postman/pay-api.postman_collection.json

*Issue #:*
https://github.com/bcgov/entity/issues/1443
Changes to pay api postman collection to reflect all the latest changes
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the entity license (Apache 2.0).

Updating pay-api postman collection

---

api-e2e/postman/auth-api.postman_collection.json

*Issue #:*
Update the postman collection for auth-api to support e2e testing.

Update auth-api postman collection

---

rfcs/rfc-TestRails.md

Please review this proposal to use a new tool for test case management.

RFC for TestRails

---

api-e2e/postman/bcol-api.postman_collection.json
api-e2e/postman/pay-api.postman_collection.json

*Issue #:*
https://github.com/bcgov/entity/issues/1671
- Adding new postman collection for BCOL API
- Removing bcol endpoints from pay-api postman collection
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the entity license (Apache 2.0).

Updating postman collection to incorporate BCOL API changes

---

api-e2e/postman/colin-api.postman_collection.json

*Issue #:*
This is the current postman sweet for the colin api (not sure when this when this was last updated)

colin-api postman changes

---

api-e2e/postman/pay-api.postman_collection.json

*Issue #:*
Updating Pay API collection to use service accounts
Updating Pay API collection to use service accounts
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the entity license (Apache 2.0).

Pay API Postman collection changes

---

docs/development.md

*Description of changes:* Added documentation for the standard development environment, which consists of:
- Windows
- Windows Subsystem for Linux 2 (WSL)
- Ubuntu latest for WSL
- VS Code

Documentation for development environment.

---

docs/development.md

Added ESLint and Jest extensions

---

docs/development.md

*Description of changes:* I added Docker documentation for WSL 

Added Docker and WSL documentation 

---

e2e/conf/dev-globals.js
e2e/tests/coops/COD.js
e2e/tests/coops/staffCOA.js
e2e/tests/coops/staffCOD.js
e2e/tests/coops/staffSearch.js

corrected dev globals

---

.github/ISSUE_TEMPLATE/pre_release_checklist.md

*Issue #:* n/a
Added to release checklist.

added addition steps/notes to release checklist.

---

e2e/conf/test-globals.js
e2e/package.json
e2e/page-objects/CodPage.js
e2e/page-objects/dashboardPage.js
e2e/tests/Proof_of_Concept/xhr-test.js
e2e/tests/coops/COD.js
e2e/tests/coops/ar.js
e2e/tests/coops/staffCOA.js
e2e/tests/coops/staffCOD.js
e2e/tests/coops/staffSearch.js

Staff filings

---

docs/Way of Working/QA-Smoke-Testing.md

*Issue #:*
#2227 
Added the start of a complete test plan. This document explains the QA process for automated smoke testing.

2227 - Create Test Plan for Entities

---

rfcs/rfc-secrets-management-1Password.md

Signed-off-by: thor wolpert <thor@wolpert.ca>
*Issue #:*n/a
- first draft of the 1Password RFC

draft of the 1Password RFC.

---

e2e/package.json

adjusted pipeline run in package.json

---

e2e/Jenkinsfile
e2e/package.json

Adjust packagejson

---

e2e/conf/pipeline.conf.js

turned on network logging

---

.github/ISSUE_TEMPLATE/OCM_Task.md

*Issue #:*
made new zenhub ticket template for ocm tasks

new zenhub ticket template

---

integration-tests/Jenkinsfiles/integration-dev-pipeline.groovy
integration-tests/Jenkinsfiles/integration-pipeline.groovy
integration-tests/Jenkinsfiles/integration-test-pipeline.groovy

*Issue bcgov/entity#3508:*
- renamed stages

renamed stages

---

integration-tests/Jenkinsfiles/integration-pipeline.groovy

int tests, add submitter

---

docs/development.md

Description of changes: 
- Separate instructions for WSL 1 and 2 to integrate with Docker in Windows
- Python upgraded to 3.8.5

WSL 1 and 2, Python upgrade

---

integration-tests/Jenkinsfiles/postman-pipeline.groovy
integration-tests/postman/lear-verify-incorp.postman_collection.json

Verify - Legal db gets updated

---

e2e/custom-commands/setupData.js

*Issue #3932 
*Description of changes:
- Call data-reset-tool by legalType
- Separate file attachment for each table

update nightwatch scripts for calling data-reset-tool

---

rfcs/rfc-shared-components.md

*Issue #:* /bcgov/entity#4551
- RFC for proposed BCRS Shared Component library

Added RFC for shared component library

---

integration-tests/Jenkinsfiles/integration-pipeline.groovy
integration-tests/postman/lear-verify-bn-updated.postman_collection.json

only verify bn if not in dev

---

integration-tests/postman/colin-verify-incorp.postman_collection.json

fixed err in colin-verify

---

integration-tests/postman/colin-verify-incorp.postman_collection.json
integration-tests/postman/lear-incorporation.postman_collection.json
integration-tests/postman/lear-verify-bn-updated.postman_collection.json

*Issue #5006:*
- see ticket for details

updated for BEN legal type

---

rfcs/rfc-covid-agm-extension.md

6198 rfc covid agm extension

---

rfcs/rfc-ppr-datatable.md

*Issue #:* https://github.com/bcgov/entity/issues/6240
- rfc for which data table to use for PPR

ppr-datatable-rfc

---

docs/coding-standards/pr-reviews.md

*Issue #:* None
This document outlines PR review guidelines.

Created pr-reviews.md

---

rfcs/rfc-filing-technical-corrections.md

*Issue #:* bcgov/entity#6618rfc
suggested fix for technical corrections to accepted filing submissions
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the entity license (Apache 2.0).

suggested fix for technical corrections to accepted filing submissions

---

rfcs/rfc-create-ui-architecture.md

RFC for a "Create UI" Architecture To Support New Filing Types

---

rfcs/rfc-business-ledger-data-structure.md

*Issue #:* bcgov/entity#7193
Initial version of the JSON that the GET filings end-point will return.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcregistry license (Apache 2.0).

describe the json being returned by the GET filings call

---

docs/devops/quarterly_review.md

*Issue #:*
https://github.com/bcgov/entity/issues/6986
Update Quarterly Review checklist to include review team member permissions in Keycloak and other third party applications.

6986-Update Quarterly Review Checklist.

---

docs/relationships/partner_onboarding.md

*Issue #:*
#7264 
- Adding partner on-boarding documentation

Partner on-boarding documentation

---

rfcs/rfc-ppr-ims-db-migration.md

*Issue #:*n/a
- draft RFC
- covering data migration approach from IMS -> Postgres
- target model management
- Search selection

first draft IMS conversion and DB change

---

rfcs/rfc-pay-admin.md

*Issue #:*
#9430 
- Short RFC on Admin UI for Pay

RFC for Pay Admin UI

---

rfcs/rfc-ppr-transaction-recovery.md

inital draft

---

api-e2e/postman/Import Routing Slip.postman_collection.json

*Issue #:*
https://github.com/bcgov/entity/issues/11467

Adding Routing Slip import post man colection

---

rfcs/rfc-replace_report_api.md

Signed-off-by: Doug Lovett <doug@diamante.ca>
*Issue #: #12930
RFC to replace the existing report api.

RFC to replace report service.

---

rfcs/rfc-auth-web-vue3-conversion.md

Signed-off-by: Kial Jinnah <kialjinnah@gmail.com>
*Issue #:*https://github.com/bcgov/entity/issues/14475

auth-web rfc for vue3 upgrade

---

rfcs/rfc-replace-SQLContinuum-with-SQLAlchemy-history.md

*Issue #:*  #16569 
Submit the RFX to migrate away from SQLAlchemy

initial rfc for 16569

---

docs/coding-standards/coding-style-fe.md
docs/coding-standards/coding-style.md

*Issue #:* None
- see file contents
- this is an initial draft, but I think it's worth merging now

created initial Code Style Guidelines

---

docs/relationships/partner_onboarding.md

Small documentation update for partner onboarding

Small documentation update for partner onboarding

---

.github/ISSUE_TEMPLATE/analytics-request-.md

I created a template for Analytics Request, to make it easy for all ad-hoc data request for modernized as well as legacy.

Update issue templates

---

.github/ISSUE_TEMPLATE/STR-host-feature.md

Updated to Developer requirements

---

.github/ISSUE_TEMPLATE/STR-host-feature.md
.github/ISSUE_TEMPLATE/feature-request---2-.md
.github/ISSUE_TEMPLATE/feature-request---idea-.md

Changes to the Host User Story Template 

---

.github/ISSUE_TEMPLATE/PPR_TEMPLATE.md

*Issue #:* n/a
- initial PRR Template
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the license (Apache 2.0).

initial prr checklist

---

.github/ISSUE_TEMPLATE/analytics-request-.md
.github/ISSUE_TEMPLATE/strr-spike.md

STRR Spike
A template for Spikes on the Short Term Rental Registry team

Added a template for Spikes for the STRR team

---

.github/ISSUE_TEMPLATE/strr---design-and-ui-layout-fixes.md
.github/ISSUE_TEMPLATE/strr---spike.md

Implementation of https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/23256

Update issue templates - Added template for Design and UI Layout Fixes

---

.github/ISSUE_TEMPLATE/strr---accessibility-fixes-.md

Added a new template for STRR Accessibility Fixes.

Update issue templates - STRR Accessibillity

---

.github/ISSUE_TEMPLATE/strr---pre-release-checklist.md

update release template

---

docs/entities/Dev_Install_Guide.md

No issue number, simple documentation update
Updated current Python Version in use, added a couple of packages required for installing Python in WSL.

Dev-Install-Guide updates

---

.github/DISCUSSION_TEMPLATE/rfc.yml

*Issue #:* n/a
Adding a RFC template to Discussions.

adding a RFC template to dicsussions
